import type { CategoryName } from "./types";

export const Qwiz_Themes: Record<CategoryName, { name: string }[]> = {
  Sports: [
    { name: "Brazilian Football" },
    { name: "English Football" },
    { name: "Spanish Football" },
    { name: "Italian Football" },
    { name: "French Football" },
    { name: "FIFA World Cups" },
    { name: "Eurocup" },
    { name: "Copa América" },
    { name: "African Cup of Nations" },
    { name: "Asian Cup" },
    { name: "UEFA Champions League" },
    { name: "CONMEBOL Libertadores" },
    { name: "NBA" },
    { name: "NFL" },
    { name: "Tennis" },
    { name: "Formula 1" },
    { name: "Olympics" },
  ],
  Geography: [
    { name: "Country Flags" },
    { name: "Capital Cities" },
    { name: "World Map" },
    { name: "Tourist Attractions" },
    { name: "Physical Geography" },
  ],
  Sciences: [
    { name: "Mathematics" },
    { name: "Physics" },
    { name: "Chemistry" },
    { name: "Astronomy" },
    { name: "Biology" },
    { name: "Human Body" },
    { name: "Planet Earth" },
    { name: "Inventions and Inventors" },
    { name: "Internet and Computers" },
  ],
  History: [
    { name: "Ancient Egypt" },
    { name: "Ancient Greece" },
    { name: "Ancient Rome" },
    { name: "Ancient Age" },
    { name: "Middle Ages" },
    { name: "Renaissance" },
    { name: "French Revolution" },
    { name: "Industrial Revolution" },
    { name: "World War I" },
    { name: "World War II" },
    { name: "Cold War" },
    { name: "Brazil" },
    { name: "Latin America" },
    { name: "United States" },
  ],
  Entertainment: [
    { name: "Famous Movies" },
    { name: "Actors and Actresses" },
    { name: "Harry Potter" },
    { name: "Marvel and DC" },
    { name: "Disney and Pixar" },
    { name: "TV Series" },
    { name: "Videogames" },
    { name: "Minecraft" },
    { name: "Call of Duty" },
    { name: "Assassin's Creed" },
    { name: "Mario Bros" },
    { name: "Grand Theft Auto" },
    { name: "Bands and Artists" },
  ],
  Arts: [
    { name: "History of Art" },
    { name: "Global Literature" },
    { name: "Paintings and Sculptures" },
    { name: "Art Movements" },
    { name: "Architecture" },
  ],
  Languages: [
    { name: "History of Languages" },
    { name: "English" },
    { name: "Portuguese" },
  ],
};
